name: QLCC-FE Deployment

on:
  push:
    branches: [main]

permissions:
  contents: read #đọc source code của repository.
  packages: write #push package vào GitHub Packages(ghcr)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4 #checkout sang nhanh kich hoat workflow (o day la main)

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build frontend image
        run: |
          cd ql_chungcu 
          docker build -t ghcr.io/${{ secrets.REPOSITORY_OWNER }}/qlcc-fe-java:${{ github.sha }} .

      - name: Push frontend image
        run: docker push ghcr.io/${{ secrets.REPOSITORY_OWNER }}/qlcc-fe-java:${{ github.sha }}

      - name: Deploy frontend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/atus/qlcc_java/deploy
            OLD_IMAGE=$(docker inspect qlcc_fe-java --format='{{.Config.Image}}' 2>/dev/null || true)
            echo "Old image: $OLD_IMAGE"

            docker stop qlcc_fe-java || true
            docker rm qlcc_fe-java || true
            
            FRONTEND_TAG=${{ github.sha }} docker compose -f docker-compose-qlcc-java.yml pull qlcc-frontend
            FRONTEND_TAG=${{ github.sha }} docker compose -f docker-compose-qlcc-java.yml up -d qlcc-frontend
            docker compose -f docker-compose-qlcc-java.yml restart nginx
            if [ -n "$OLD_IMAGE" ]; then docker image rm "$OLD_IMAGE" || true; fi
            docker ps

            echo "Frontend deployment completed"
